runtime: python312  # Ensure the correct Python version

entrypoint: gunicorn -b :$PORT main:app  # Ensure 'main' matches your Python file

instance_class: F1  # Choose instance class (F1 is the smallest)

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

# Fetch API key securely from Secret Manager
env_variables:
  OPENAI_API_KEY: "{{secret:OPENAI_API_KEY}}"

