name: Deploy to Google Kubernetes Engine (GKE)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure gcloud CLI
      run: |
        gcloud config set project nudgeme-450123
        gcloud auth configure-docker us-central1-docker.pkg.dev

    # --- BUILD & PUSH AI SERVICE ---
    - name: Build and Push AI Service
      run: |
        cd ai_service
        docker build -t us-central1-docker.pkg.dev/nudgeme-450123/my-docker-repo/ai-service:latest .
        docker push us-central1-docker.pkg.dev/nudgeme-450123/my-docker-repo/ai-service:latest

    # --- BUILD & PUSH UPLOAD SERVICE ---
    - name: Build and Push Upload Service
      run: |
        cd upload_service
        docker build -t us-central1-docker.pkg.dev/nudgeme-450123/my-docker-repo/upload-service:latest .
        docker push us-central1-docker.pkg.dev/nudgeme-450123/my-docker-repo/upload-service:latest

    # --- UPDATE KUBERNETES DEPLOYMENTS ---
    - name: Get Kubernetes Cluster Credentials
      run: |
        gcloud container clusters get-credentials finance-cluster --region us-central1

    - name: Deploy AI Service to Kubernetes
      run: |
        kubectl set image deployment/ai-service ai-service=us-central1-docker.pkg.dev/nudgeme-450123/my-docker-repo/ai-service:latest --record

    - name: Deploy Upload Service to Kubernetes
      run: |
        kubectl set image deployment/upload-service upload-service=us-central1-docker.pkg.dev/nudgeme-450123/my-docker-repo/upload-service:latest --record

    - name: Verify Deployments
      run: |
        kubectl get pods
        kubectl get services
